/**
 * Mock data for Character Assignment Page
 */

import { CharacterRole } from "@/lib/apiTypes"
import { CharacterCategory } from "@/types"

/**
 * Mock preset characters available for assignment
 * These match the actual character images in /public/characters/
 */
export const mockPresetCharacters = [
  // Female characters
  {
    id: "char_f_amelia",
    name: "Amelia",
    imageUrl: "/characters/f_amelia.png",
    category: CharacterCategory.HUMAN,
    description: "A curious and brave young girl",
  },
  {
    id: "char_f_ava",
    name: "Ava",
    imageUrl: "/characters/f_ava.png",
    category: CharacterCategory.HUMAN,
    description: "A kind and helpful friend",
  },
  {
    id: "char_f_emma",
    name: "Emma",
    imageUrl: "/characters/f_emma.png",
    category: CharacterCategory.HUMAN,
    description: "A wise and gentle helper",
  },
  {
    id: "char_f_olivia",
    name: "Olivia",
    imageUrl: "/characters/f_olivia.png",
    category: CharacterCategory.HUMAN,
    description: "A cheerful and energetic companion",
  },
  {
    id: "char_f_sophia",
    name: "Sophia",
    imageUrl: "/characters/f_sophia.png",
    category: CharacterCategory.HUMAN,
    description: "A clever and resourceful character",
  },
  // Male characters
  {
    id: "char_m_james",
    name: "James",
    imageUrl: "/characters/m_james.png",
    category: CharacterCategory.HUMAN,
    description: "A strong and loyal friend",
  },
  {
    id: "char_m_john",
    name: "John",
    imageUrl: "/characters/m_john.png",
    category: CharacterCategory.HUMAN,
    description: "A brave and adventurous hero",
  },
  {
    id: "char_m_joseph",
    name: "Joseph",
    imageUrl: "/characters/m_joseph.png",
    category: CharacterCategory.HUMAN,
    description: "A wise and patient mentor",
  },
  {
    id: "char_m_noah",
    name: "Noah",
    imageUrl: "/characters/m_noah.png",
    category: CharacterCategory.HUMAN,
    description: "A creative and artistic soul",
  },
  {
    id: "char_m_william",
    name: "William",
    imageUrl: "/characters/m_william.png",
    category: CharacterCategory.HUMAN,
    description: "A determined and focused achiever",
  },
]

/**
 * Mock story roles for character assignment
 * These are the 4 roles generated by AI for the story
 */
export const mockStoryRoles: CharacterRole[] = [
  {
    id: "role_001",
    role: "Protagonist",
    description:
      "A brave young hero who learns the importance of honesty through their journey",
  },
  {
    id: "role_002",
    role: "Best Friend",
    description:
      "The protagonist's loyal companion who supports them through challenges",
  },
  {
    id: "role_003",
    role: "Wise Helper",
    description:
      "A mentor figure who provides guidance and wisdom at crucial moments",
  },
  {
    id: "role_004",
    role: "Antagonist",
    description:
      "The challenge or obstacle that the protagonist must overcome to learn the lesson",
  },
]

/**
 * Mock existing assignments (partially completed)
 * Used to test loading existing assignment state
 */
export const mockExistingAssignments = {
  role_001: {
    characterRoleId: "role_001",
    presetCharacterId: "char_f_amelia",
    role: "Protagonist",
    characterName: "Amelia",
    imageUrl: "/characters/f_amelia.png",
  },
  role_003: {
    characterRoleId: "role_003",
    presetCharacterId: "char_m_joseph",
    role: "Wise Helper",
    characterName: "Joseph",
    imageUrl: "/characters/m_joseph.png",
  },
}

/**
 * Mock API response for fetching preset characters
 */
export const mockCharactersResponse = {
  success: true,
  data: {
    characters: mockPresetCharacters,
  },
}

/**
 * Mock API response for fetching story roles
 */
export const mockStoryRolesResponse = {
  success: true,
  data: {
    storyId: "story_12345",
    characters: mockStoryRoles,
  },
}

/**
 * Mock API response for fetching existing assignments
 */
export const mockAssignmentsResponse = {
  success: true,
  data: {
    storyId: "story_12345",
    assignments: Object.values(mockExistingAssignments),
  },
}

/**
 * Mock API response for saving assignments
 */
export const mockSaveAssignmentsResponse = {
  success: true,
  data: {
    storyId: "story_12345",
    assignments: [
      {
        characterRoleId: "role_001",
        presetCharacterId: "char_f_amelia",
        role: "Protagonist",
        characterName: "Amelia",
        imageUrl: "/characters/f_amelia.png",
      },
      {
        characterRoleId: "role_002",
        presetCharacterId: "char_f_ava",
        role: "Best Friend",
        characterName: "Ava",
        imageUrl: "/characters/f_ava.png",
      },
      {
        characterRoleId: "role_003",
        presetCharacterId: "char_m_joseph",
        role: "Wise Helper",
        characterName: "Joseph",
        imageUrl: "/characters/m_joseph.png",
      },
      {
        characterRoleId: "role_004",
        presetCharacterId: "char_m_john",
        role: "Antagonist",
        characterName: "John",
        imageUrl: "/characters/m_john.png",
      },
    ],
  },
}

/**
 * Simulate API delay for realistic testing
 */
export const simulateDelay = (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms))
