/**
 * Mock Data for Story Selection Page
 *
 * Contains sample completed stories for development and testing
 */

import { Story, StoryStatus } from "@/types"

/**
 * Mock completed stories with variety
 */
export const mockCompletedStories: Story[] = [
  {
    id: "story-001",
    title: "The Lost Treasure of Honesty Island",
    lesson: "Honesty is always the best policy",
    theme: "Honesty",
    format: "Adventure",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-10-01T10:00:00Z",
    updatedAt: "2025-10-15T14:30:00Z",
    sceneCount: 7,
    readCount: 145,
    isPublished: true,
    authorId: "user-001",
    coverImageUrl: "/images/backgrounds/enchanted-forest-v1.png",
  },
  {
    id: "story-002",
    title: "The Courage of the Little Dragon",
    lesson: "Being brave means facing your fears",
    theme: "Courage",
    format: "Fantasy",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-09-28T14:00:00Z",
    updatedAt: "2025-10-12T16:00:00Z",
    sceneCount: 8,
    readCount: 267,
    isPublished: true,
    authorId: "user-001",
    coverImageUrl: "/images/backgrounds/crystal-cave-v1.png",
  },
  {
    id: "story-003",
    title: "Friends in the Enchanted Forest",
    lesson: "True friends support each other",
    theme: "Friendship",
    format: "Fantasy",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-10-05T08:00:00Z",
    updatedAt: "2025-10-16T10:00:00Z",
    sceneCount: 6,
    readCount: 189,
    isPublished: true,
    authorId: "user-002",
    coverImageUrl: "/images/backgrounds/wooden-bridge-v1.png",
  },
  {
    id: "story-004",
    title: "The Kind Robot's Gift",
    lesson: "Kindness creates happiness for everyone",
    theme: "Kindness",
    format: "Science Fiction",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-10-08T12:00:00Z",
    updatedAt: "2025-10-17T15:00:00Z",
    sceneCount: 5,
    readCount: 98,
    isPublished: true,
    authorId: "user-001",
    coverImageUrl: "/images/backgrounds/crystal-cave-v2.png",
  },
  {
    id: "story-005",
    title: "Sharing at the Moon Party",
    lesson: "Sharing makes celebrations better",
    theme: "Sharing",
    format: "Fantasy",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-09-25T09:30:00Z",
    updatedAt: "2025-10-10T11:00:00Z",
    sceneCount: 6,
    readCount: 312,
    isPublished: true,
    authorId: "user-002",
    coverImageUrl: "/images/backgrounds/enchanted-forest-v2.png",
  },
  {
    id: "story-006",
    title: "The Teamwork Treasure Hunt",
    lesson: "Working together helps us achieve more",
    theme: "Teamwork",
    format: "Adventure",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-10-10T14:00:00Z",
    updatedAt: "2025-10-18T09:00:00Z",
    sceneCount: 9,
    readCount: 76,
    isPublished: true,
    authorId: "user-001",
    coverImageUrl: "/images/backgrounds/crystal-cave-v3.png",
  },
  {
    id: "story-007",
    title: "The Grateful Garden",
    lesson: "Being thankful brings joy",
    theme: "Gratitude",
    format: "Fairy Tale",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-09-20T10:00:00Z",
    updatedAt: "2025-10-05T12:00:00Z",
    sceneCount: 5,
    readCount: 423,
    isPublished: true,
    authorId: "user-002",
    coverImageUrl: "/images/backgrounds/enchanted-forest-v1.png",
  },
  {
    id: "story-008",
    title: "Never Give Up Mountain",
    lesson: "Perseverance helps us reach our goals",
    theme: "Perseverance",
    format: "Adventure",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-10-12T08:00:00Z",
    updatedAt: "2025-10-17T14:00:00Z",
    sceneCount: 7,
    readCount: 134,
    isPublished: true,
    authorId: "user-001",
    coverImageUrl: "/images/backgrounds/wooden-bridge-v1.png",
  },
  {
    id: "story-009",
    title: "Respect in the Royal Castle",
    lesson: "Treating others with respect is important",
    theme: "Respect",
    format: "Fairy Tale",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-10-02T11:00:00Z",
    updatedAt: "2025-10-14T16:00:00Z",
    sceneCount: 6,
    readCount: 201,
    isPublished: true,
    authorId: "user-002",
    coverImageUrl: "/images/backgrounds/crystal-cave-v1.png",
  },
  {
    id: "story-010",
    title: "The Responsible Pet Detective",
    lesson: "Being responsible means following through",
    theme: "Responsibility",
    format: "Mystery",
    status: StoryStatus.COMPLETED,
    createdAt: "2025-10-15T13:00:00Z",
    updatedAt: "2025-10-18T10:00:00Z",
    sceneCount: 8,
    readCount: 52,
    isPublished: true,
    authorId: "user-001",
    coverImageUrl: "/images/backgrounds/crystal-cave-v2.png",
  },
]

/**
 * Empty state content when no stories are available
 */
export const mockEmptyState = {
  title: "No Stories Yet!",
  message: "Ask a parent to create a wonderful story for you!",
  icon: "📚",
}
